# Generated by Django 5.0.2 on 2024-02-27 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=155, verbose_name='name')),
                ('name_en', models.CharField(max_length=155, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=155, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=155, null=True, verbose_name='name')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=155, verbose_name='name')),
                ('name_en', models.CharField(max_length=155, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=155, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=155, null=True, verbose_name='name')),
            ],
            options={
                'db_table': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=155, verbose_name='name')),
                ('name_en', models.CharField(max_length=155, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=155, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=155, null=True, verbose_name='name')),
            ],
            options={
                'db_table': 'Size',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=155, verbose_name='name')),
                ('name_en', models.CharField(max_length=155, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=155, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=155, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', to='files.file')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='catalog.category', verbose_name='category')),
            ],
            options={
                'db_table': 'Catalog',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('vendor_code', models.CharField(max_length=100, verbose_name='vendor code')),
                ('price', models.FloatField(verbose_name='price')),
                ('discount', models.FloatField(verbose_name='discount')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.catalog', verbose_name='catalog')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.color', verbose_name='color')),
                ('miniature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miniature_specs', to='files.file', verbose_name='miniature')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_specs', to='files.file', verbose_name='photo')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.size', verbose_name='size')),
            ],
            options={
                'db_table': 'Specification',
            },
        ),
    ]
